
"project_id_env": "CROWDIN_ID"
"api_token_env": "CROWDIN_TOKEN"
"base_path": "."

"preserve_hierarchy": true
files: [
    {
        "source": "src/main/resources/assets/betterbiomes/lang/en_us.json",
        "translation": "src/main/resources/assets/betterbiomes/lang/%locale_with_underscore%.json",
    }
]