modLoader="javafml"
loaderVersion="[47,)"
license="All rights reserved"
showAsResourcePack=false

[[mods]]
modId="betterbiomes"
version="0.1.4.2"
displayName="Better Biomes"
logoFile="logo.png"
credits="MochaComa"
authors="CrypticVerse"
description=''' Adds Many Different Biomes to the game!'''

[[dependencies.betterbiomes]]
modId="forge"
mandatory=true
versionRange="[47,)"
ordering="NONE"
side="BOTH"

[[dependencies.betterbiomes]]
modId="minecraft"
mandatory=true
versionRange="[1.20,1.21)"
ordering="NONE"

[[dependencies.betterbiomes]]
modId="terrablender"
mandatory=true
versionRange="[3.0.0.169,)"
ordering="NONE"